services:
  mint-redeem:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ${CI_REGISTRY_IMAGE}:${DEPLOY_IMAGE_TAG}
    command: ["mint-redeem"]
    restart: unless-stopped
    environment:
      CONFIG: /app/config.toml
      CHAIN: ${CHAIN}
      NAT_RPC_URL: ${NAT_RPC_URL}
      NAT_RPC_API_KEY: ${NAT_RPC_API_KEY}
      XRP_RPC_URL: ${XRP_RPC_URL}
      XRP_RPC_API_KEY: ${XRP_RPC_API_KEY}
      XRP_DISTRIBUTOR_SEED: ${XRP_DISTRIBUTOR_SEED}
    volumes:
      - ${CONFIG}:/app/config.toml
      - ./accounts:/app/accounts
      - ./smart-accounts-logs:/app/logs
